name: Verify version & schemas
on:
  pull_request:
    paths:
      - 'docs/api.yaml'
      - 'VERSION'
      - 'CHANGELOG.md'
      - '.github/workflows/verify-version-and-schemas.yml'
      - 'docs/**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read VERSION
        id: ver
        run: echo "VER=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Verify OpenAPI version matches VERSION
        run: |
          OAS_VER=$(grep -E '^  version:' -n docs/api.yaml | head -n1 | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
          echo "OAS_VER=$OAS_VER"
          echo "FILE_VER=${{ steps.ver.outputs.VER }}"
          if [ "$OAS_VER" != "${{ steps.ver.outputs.VER }}" ]; then
            echo "::error ::docs/api.yaml.info.version ($OAS_VER) non combacia con VERSION (${{ steps.ver.outputs.VER }})"
            exit 1
          fi

      - name: Fail if api.yaml changed without VERSION bump
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }}... | grep -q '^docs/api.yaml$'; then
            # Se api.yaml è cambiato, VERSION deve cambiare
            if ! git diff --name-only origin/${{ github.base_ref }}... | grep -q '^VERSION$'; then
              echo "::error ::docs/api.yaml è stato modificato senza bump di VERSION"
              exit 1
            fi
          fi