openapi: 3.0.3
info:
  title: Tasks & Tags API
  version: "1.1.0"
  description: >
    API minima per gestione Task e Tag. **Sorgente di Verità** in questo file: ogni modifica richiede PR e bump versione.
servers:
  - url: https://api.example.com
    description: Placeholder server (aggiornare in app)
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Tasks
  - name: Tags
  - name: Auth
paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticazione riuscita
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401': { description: Credenziali non valide }
  /auth/logout:
    post:
      tags: [Auth]
      summary: Logout
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout completato
        '401': { description: Non autenticato }
      security:
        - bearerAuth: []
  /auth/me:
    get:
      tags: [Auth]
      summary: Profilo utente autenticato
      operationId: me
      responses:
        '200':
          description: Dati utente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
        '401': { description: Non autenticato }
      security:
        - bearerAuth: []
  /health:
    get:
      summary: Healthcheck
      operationId: health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /tasks:
    get:
      summary: List tasks
      operationId: listTasks
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema: { type: string }
          description: Ricerca testuale semplice
        - in: query
          name: tag
          schema: { type: string }
          description: Slug tag singolo per filtrare
        - in: query
          name: status
          schema: { type: string, enum: [todo, doing, done, blocked] }
      responses:
        '200':
          description: Elenco di Task
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create task
      operationId: createTask
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Get task
      operationId: getTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Dettaglio Task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404': { description: Not Found }
    patch:
      summary: Update task
      operationId: updateTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Aggiornato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404': { description: Not Found }
    delete:
      summary: Delete task
      operationId: deleteTask
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '204': { description: Deleted }
        '404': { description: Not Found }
  /tags:
    get:
      summary: List tags
      operationId: listTags
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Elenco di Tag
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    post:
      summary: Create tag
      operationId: createTag
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
  /tags/{id}:
    get:
      summary: Get tag
      operationId: getTag
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Dettaglio Tag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404': { description: Not Found }
    patch:
      summary: Update tag
      operationId: updateTag
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
      responses:
        '200':
          description: Aggiornato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404': { description: Not Found }
    delete:
      summary: Delete tag
      operationId: deleteTag
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '204': { description: Deleted }
        '404': { description: Not Found }

components:
  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema: { type: string }
  schemas:
    Error:
      type: object
      required: [message]
      properties:
        message: { type: string }
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email: { type: string, format: email }
        password: { type: string, format: password }
    LoginResponse:
      type: object
      required: [token, user]
      properties:
        token: { type: string, description: "Bearer token" }
        user:
          $ref: '#/components/schemas/User'
    MeResponse:
      $ref: '#/components/schemas/User'
    User:
      type: object
      required: [id, email]
      properties:
        id: { type: string, example: "usr_123" }
        email: { type: string, format: email }
        name: { type: string, nullable: true }
    Task:
      type: object
      required: [id, title, status, tags]
      properties:
        id: { type: string, example: "tsk_123" }
        title: { type: string }
        description: { type: string, nullable: true }
        status: { type: string, enum: [todo, doing, done, blocked], default: todo }
        assignee: { type: string, nullable: true, description: "Identifier of the assignee" }
        due_date: { type: string, format: date, nullable: true }
        tags:
          type: array
          items: { $ref: '#/components/schemas/TagRef' }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    TaskCreate:
      type: object
      required: [title]
      properties:
        title: { type: string }
        description: { type: string, nullable: true }
        status: { type: string, enum: [todo, doing, done, blocked] }
        assignee: { type: string, nullable: true }
        due_date: { type: string, format: date, nullable: true }
        tags:
          type: array
          items: { type: string, description: "Tag slug" }
    TaskUpdate:
      type: object
      properties:
        title: { type: string }
        description: { type: string, nullable: true }
        status: { type: string, enum: [todo, doing, done, blocked] }
        assignee: { type: string, nullable: true }
        due_date: { type: string, format: date, nullable: true }
        tags:
          type: array
          items: { type: string, description: "Tag slug" }
    Tag:
      type: object
      required: [id, name, slug]
      properties:
        id: { type: string, example: "tag_123" }
        name: { type: string }
        slug: { type: string }
        color: { type: string, nullable: true, example: "#7c3aed" }
        parent: { $ref: '#/components/schemas/TagRef', nullable: true }
    TagCreate:
      type: object
      required: [name, slug]
      properties:
        name: { type: string }
        slug: { type: string }
        color: { type: string, nullable: true }
        parent_slug: { type: string, nullable: true }
    TagUpdate:
      type: object
      properties:
        name: { type: string }
        slug: { type: string }
        color: { type: string, nullable: true }
        parent_slug: { type: string, nullable: true }
    TagRef:
      type: object
      required: [slug, name]
      properties:
        slug: { type: string }
        name: { type: string }